services:
  config-manager:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile.config-manager
      args:
        - CM_AGENT_DIRECTORY=${CM_AGENT_DIRECTORY:-/root/data}
        - CM_SERVER_PORT=${CM_SERVER_PORT:-8080}
    ports:
      - "${CM_SERVER_PORT:-8080}:${CM_SERVER_PORT:-8080}"
    volumes:
      - ${HOST_DATA_DIR:-../../data}:${CM_AGENT_DIRECTORY:-/root/data}
    environment:
      - CM_LOG_LEVEL=${CM_LOG_LEVEL:-info}
