services:
  config-manager:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile.config-manager
    ports:
      - "8080:8080"
    volumes:
      - ../../data:/root/data
    environment:
      - LOG_LEVEL=info