export const testIds = {
  appConfig: {
    submit: 'data-testid ac-submit-form',
    testConnection: 'data-testid ac-test-connection',
    testCbResult: 'data-testid ac-test-cb',
    testDsResult: 'data-testid ac-test-ds',
    couchbaseConnectionString: 'data-testid ac-cb-conn',
    couchbaseUsername: 'data-testid ac-cb-user',
    couchbasePassword: 'data-testid ac-cb-pass',
    snapshotsEnabled: 'data-testid ac-snap-enabled',
    snapshotsBucket: 'data-testid ac-snap-bucket',
    snapshotsScope: 'data-testid ac-snap-scope',
    snapshotsCollection: 'data-testid ac-snap-collection',
    couchbaseDsEnabled: 'data-testid ac-cbds-enabled',
    couchbaseDsBucket: 'data-testid ac-cbds-bucket',
    couchbaseDsScope: 'data-testid ac-cbds-scope',
    couchbaseDsCollection: 'data-testid ac-cbds-collection',
    prometheusDsEnabled: 'data-testid ac-prom-enabled',
    prometheusDsDefault: 'data-testid ac-prom-default',
    prometheusDsUrl: 'data-testid ac-prom-url',
  },
  home: {
    container: 'data-testid home-container',
    searchInput: 'data-testid home-search-input',
    searchButton: 'data-testid home-search-button',
  },
};
