# Config Manager Service Configuration
server:
  port: 8080
  host: "0.0.0.0"

agent:
  type: "vmagent"  # or "alloy" or "prometheus"
  directory: "./temp_path"

logging:
  level: "info"

manager:
  interval: 2m
  min_interval: 5m
  stale_threshold: 5m

# Metadata configuration for storing cluster metadata in Couchbase
metadata:
  enabled: true
  host: "localhost"
  bucket: "metadata"
  timeout: 30s
