{
 "title": "index_basic",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "snapshot",
    "label": "Job",
    "query": "SELECT DISTINCT d.labels.job FROM cbmonitor._default._default AS d WHERE d.labels.job IS NOT NULL"
   },
   {
    "name": "index",
    "label": "Index",
    "query": "SELECT DISTINCT d.labels.`index` FROM cbmonitor._default._default AS d WHERE d.labels.`index` IS NOT NULL"
   }
  ]
 },
 "panels": [
  {
   "title": "Index Disk Bytes per Second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM metrics_filter(\"index_avg_disk_bps\", '$snapshot', \"172.23.96.223:8091\", NULL) AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM metrics_filter(\"index_avg_disk_bps\", '$snapshot', \"172.23.96.97:8091\", NULL) AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "Index Mutation Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM metrics_filter(\"index_avg_mutation_rate\", '$snapshot', \"172.23.96.223:8091\", NULL) AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM metrics_filter(\"index_avg_mutation_rate\", '$snapshot', \"172.23.96.97:8091\", NULL) AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "Index Average Scan Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM metrics_filter(\"index_net_avg_scan_rate\", '$snapshot', \"172.23.96.223:8091\", NULL) AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM metrics_filter(\"index_net_avg_scan_rate\", '$snapshot', \"172.23.96.97:8091\", NULL) AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "Indexer Process Resident Set Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM metrics_filter(\"index_memory_rss\", '$snapshot', \"172.23.96.223:8091\", NULL) AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM metrics_filter(\"index_memory_rss\", '$snapshot', \"172.23.96.97:8091\", NULL) AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "Index Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `cbmonitor-172.23.96.223`\nFROM metrics_filter(\"index_memory_used\", '$snapshot', \"172.23.96.223:8091\", \"cbmonitor\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `cbmonitor-172.23.96.97`\nFROM metrics_filter(\"index_memory_used\", '$snapshot', \"172.23.96.97:8091\", \"cbmonitor\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `metadata-172.23.96.223`\nFROM metrics_filter(\"index_memory_used\", '$snapshot', \"172.23.96.223:8091\", \"metadata\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `metadata-172.23.96.97`\nFROM metrics_filter(\"index_memory_used\", '$snapshot', \"172.23.96.97:8091\", \"metadata\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "Total Index Data Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM metrics_filter(\"index_total_data_size\", '$snapshot', \"172.23.96.223:8091\", NULL) AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM metrics_filter(\"index_total_data_size\", '$snapshot', \"172.23.96.97:8091\", NULL) AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "Index Average Item Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `cbmonitor`\nFROM metrics_filter(\"index_avg_item_size\", '$snapshot', NULL, \"cbmonitor\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`index` = '$index' OR '$index' = \"\")"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `metadata`\nFROM metrics_filter(\"index_avg_item_size\", '$snapshot', NULL, \"metadata\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`index` = '$index' OR '$index' = \"\")"
    }
   ]
  },
  {
   "title": "Index Average Scan Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `cbmonitor`\nFROM metrics_filter(\"index_avg_scan_latency\", '$snapshot', NULL, \"cbmonitor\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`index` = '$index' OR '$index' = \"\")"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `metadata`\nFROM metrics_filter(\"index_avg_scan_latency\", '$snapshot', NULL, \"metadata\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`index` = '$index' OR '$index' = \"\")"
    }
   ]
  },
  {
   "title": "Index Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `cbmonitor`\nFROM metrics_filter(\"index_cache_hits\", '$snapshot', NULL, \"cbmonitor\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`index` = '$index' OR '$index' = \"\")"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `metadata`\nFROM metrics_filter(\"index_cache_hits\", '$snapshot', NULL,\"metadata\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`index` = '$index' OR '$index' = \"\")"
    }
   ]
  },
  {
   "title": "Index Cache Misses",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `cbmonitor`\nFROM metrics_filter(\"index_cache_misses\", '$snapshot', NULL, \"cbmonitor\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`index` = '$index' OR '$index' = \"\")"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `metadata`\nFROM metrics_filter(\"index_cache_misses\", '$snapshot', NULL, \"metadata\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`index` = '$index' OR '$index' = \"\")"
    }
   ]
  },
  {
   "title": "Index Number of Requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `metadata`\nFROM metrics_filter(\"index_num_requests\", '$snapshot', NULL, \"metadata\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`index` = '$index' OR '$index' = \"\")"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `cbmonitor`\nFROM metrics_filter(\"index_num_requests\", '$snapshot', NULL, \"cbmonitor\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`index` = '$index' OR '$index' = \"\")"
    }
   ]
  },
  {
   "title": "Index Number of Rows Returned",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `cbmonitor`\nFROM metrics_filter(\"index_num_rows_returned\", '$snapshot', NULL, \"cbmonitor\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`index` = '$index' OR '$index' = \"\")"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `metadata`\nFROM metrics_filter(\"index_num_rows_returned\", '$snapshot', NULL, \"metadata\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`index` = '$index' OR '$index' = \"\")"
    }
   ]
  },
  {
   "title": "Index Number of Documents Indexed",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `cbmonitor`\nFROM metrics_filter(\"index_num_docs_indexed\", '$snapshot', NULL, \"cbmonitor\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`index` = '$index' OR '$index' = \"\")"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `metadata`\nFROM metrics_filter(\"index_num_docs_indexed\", '$snapshot', NULL, \"metadata\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`index` = '$index' OR '$index' = \"\")"
    }
   ]
  },
  {
   "title": "Index Items Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `cbmonitor`\nFROM metrics_filter(\"index_items_count\", '$snapshot', NULL, \"cbmonitor\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`index` = '$index' OR '$index' = \"\")"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `metadata`\nFROM metrics_filter(\"index_items_count\", '$snapshot', NULL, \"metadata\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`index` = '$index' OR '$index' = \"\")"
    }
   ]
  },
  {
   "title": "Index Disk Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `cbmonitor`\nFROM metrics_filter(\"index_disk_size\", '$snapshot', NULL, \"cbmonitor\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`index` = '$index' OR '$index' = \"\")"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `metadata`\nFROM metrics_filter(\"index_disk_size\", '$snapshot', NULL, \"metadata\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`index` = '$index' OR '$index' = \"\")"
    }
   ]
  }
 ]
}