{
 "title": "kv_demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "snapshot",
    "label": "Job",
    "query": "SELECT DISTINCT d.labels.job FROM cbmonitor._default._default AS d WHERE d.labels.job IS NOT NULL"
   }
  ]
 },
 "panels": [
  {
   "title": "sys_cpu_utilization_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS `time`, \n           t._v0 AS `value`\n    FROM cbmonitor._default._default AS d\n    UNNEST _timeseries(d, {\"ts_ranges\": [${__from}, ${__to}]}) AS t\n    WHERE d.metric_name = \"sys_cpu_utilization_rate\"\n    AND ('$snapshot' = 'All' OR d.labels.job = '$snapshot')\n      AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "ep_queue_size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS `time`, \n           t._v0 AS `value`\n    FROM cbmonitor._default._default AS d\n    UNNEST _timeseries(d, {\"ts_ranges\": [${__from}, ${__to}]}) AS t\n    WHERE d.metric_name = \"kv_ep_queue_size\"\n    AND ('$snapshot' = 'All' OR d.labels.job = '$snapshot')\n      AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "ep_diskqueue_fill",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS `time`, \n           t._v0 AS `value`\n    FROM cbmonitor._default._default AS d\n    UNNEST _timeseries(d, {\"ts_ranges\": [${__from}, ${__to}]}) AS t\n    WHERE d.metric_name = \"kv_ep_diskqueue_fill\"\n    AND ('$snapshot' = 'All' OR d.labels.job = '$snapshot')\n      AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "ep_diskqueue_drain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS `time`, \n           t._v0 AS `value`\n    FROM cbmonitor._default._default AS d\n    UNNEST _timeseries(d, {\"ts_ranges\": [${__from}, ${__to}]}) AS t\n    WHERE d.metric_name = \"kv_ep_diskqueue_drain\"\n    AND ('$snapshot' = 'All' OR d.labels.job = '$snapshot')\n      AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "ep-meta-data-mem-bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS `time`, \n           t._v0 AS `value`\n    FROM cbmonitor._default._default AS d\n    UNNEST _timeseries(d, {\"ts_ranges\": [${__from}, ${__to}]}) AS t\n    WHERE d.metric_name = \"kv_ep_meta_data_memory_bytes\"\n    AND ('$snapshot' = 'All' OR d.labels.job = '$snapshot')\n      AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "curr_items",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS `time`, \n           t._v0 AS `value`\n    FROM cbmonitor._default._default AS d\n    UNNEST _timeseries(d, {\"ts_ranges\": [${__from}, ${__to}]}) AS t\n    WHERE d.metric_name = \"kv_curr_items\"\n    AND ('$snapshot' = 'All' OR d.labels.job = '$snapshot')\n      AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "curr_connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS `time`, \n           t._v0 AS `value`\n    FROM cbmonitor._default._default AS d\n    UNNEST _timeseries(d, {\"ts_ranges\": [${__from}, ${__to}]}) AS t\n    WHERE d.metric_name = \"kv_curr_connections\"\n    AND ('$snapshot' = 'All' OR d.labels.job = '$snapshot')\n      AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "ops ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS `time`, \n           t._v0 AS `value`\n    FROM cbmonitor._default._default AS d\n    UNNEST _timeseries(d, {\"ts_ranges\": [${__from}, ${__to}]}) AS t\n    WHERE d.metric_name = \"kv_ops\"\n    AND ('$snapshot' = 'All' OR d.labels.job = '$snapshot')\n      AND time_range(t._t)"
    }
   ]
  }
 ]
}