{
 "title": "sgw_basic",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "snapshot",
    "label": "Job",
    "query": "SELECT DISTINCT d.labels.job FROM cbmonitor._default._default AS d WHERE d.labels.job IS NOT NULL"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "SELECT DISTINCT d.labels.`database` FROM cbmonitor._default._default AS d WHERE d.labels.`database` IS NOT NULL"
   }
  ]
 },
 "panels": [
  {
   "title": "sgw_resource_utilization_process_memory_resident",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_resource_utilization_process_memory_resident`\nFROM metrics_filter(\"sgw_resource_utilization_process_memory_resident\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "system_memory_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_resource_utilization_system_memory_total`\nFROM metrics_filter(\"sgw_resource_utilization_system_memory_total\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "pub_net_bytes_sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `pub_net_bytes_sent`\nFROM metrics_filter(\"sgw_resource_utilization_pub_net_bytes_sent\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "pub_net_bytes_recv",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_resource_utilization_pub_net_bytes_recv`\nFROM metrics_filter(\"sgw_resource_utilization_pub_net_bytes_recv\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "sgw_resource_utilization_admin_net_bytes_recv",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_resource_utilization_admin_net_bytes_recv`\nFROM metrics_filter(\"sgw_resource_utilization_admin_net_bytes_recv\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "sgw_resource_utilization_admin_net_bytes_sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_resource_utilization_admin_net_bytes_sent`\nFROM metrics_filter(\"sgw_resource_utilization_admin_net_bytes_sent\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "sgw_resource_utilization_num_goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_resource_utilization_num_goroutines`\nFROM metrics_filter(\"sgw_resource_utilization_num_goroutines\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "sgw_resource_utilization_goroutines_high_watermark",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_resource_utilization_goroutines_high_watermark`\nFROM metrics_filter(\"sgw_resource_utilization_goroutines_high_watermark\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "sgw_resource_utilization_go_memstats_sys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_resource_utilization_go_memstats_sys`\nFROM metrics_filter(\"sgw_resource_utilization_go_memstats_sys\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "sgw_resource_utilization_go_memstats_pausetotalns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_resource_utilization_go_memstats_pausetotalns`\nFROM metrics_filter(\"sgw_resource_utilization_go_memstats_pausetotalns\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "sgw_resource_utilization_go_memstats_heapalloc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_resource_utilization_go_memstats_heapalloc`\nFROM metrics_filter(\"sgw_resource_utilization_go_memstats_heapalloc\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "sgw_resource_utilization_go_memstats_heapidle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_resource_utilization_go_memstats_heapidle`\nFROM metrics_filter(\"sgw_resource_utilization_go_memstats_heapidle\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "sgw_resource_utilization_go_memstats_heapinuse",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_resource_utilization_go_memstats_heapinuse`\nFROM metrics_filter(\"sgw_resource_utilization_go_memstats_heapinuse\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "sgw_resource_utilization_go_memstats_heapreleased",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_resource_utilization_go_memstats_heapreleased`\nFROM metrics_filter(\"sgw_resource_utilization_go_memstats_heapreleased\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "sgw_resource_utilization_go_memstats_stackinuse",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_resource_utilization_go_memstats_stackinuse`\nFROM metrics_filter(\"sgw_resource_utilization_go_memstats_stackinuse\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": " sgw_resource_utilization_go_memstats_stacksys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_resource_utilization_go_memstats_stacksys`\nFROM metrics_filter(\"sgw_resource_utilization_go_memstats_stacksys\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "sgw_resource_utilization_error_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_resource_utilization_error_count`\nFROM metrics_filter(\"sgw_resource_utilization_error_count\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "sgw_resource_utilization_warn_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_resource_utilization_warn_count`\nFROM metrics_filter(\"sgw_resource_utilization_warn_count\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "sgw_cache_chan_cache_max_entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_cache_chan_cache_max_entries`\nFROM metrics_filter(\"sgw_cache_chan_cache_max_entries\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_cache_chan_cache_hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_cache_chan_cache_hits`\nFROM metrics_filter(\"sgw_cache_chan_cache_hits\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_cache_chan_cache_misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_cache_chan_cache_misses`\nFROM metrics_filter(\"sgw_cache_chan_cache_misses\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_cache_chan_cache_pending_queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_cache_chan_cache_pending_queries`\nFROM metrics_filter(\"sgw_cache_chan_cache_pending_queries\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_cache_chan_cache_num_channels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_cache_chan_cache_num_channels`\nFROM metrics_filter(\"sgw_cache_chan_cache_num_channels\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_cache_chan_cache_removal_revs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_cache_chan_cache_removal_revs`\nFROM metrics_filter(\"sgw_cache_chan_cache_removal_revs\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_cache_chan_cache_tombstone_revs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_cache_chan_cache_tombstone_revs`\nFROM metrics_filter(\"sgw_cache_chan_cache_tombstone_revs\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_cache_chan_cache_active_revs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_cache_chan_cache_active_revs`\nFROM metrics_filter(\"sgw_cache_chan_cache_active_revs\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_cache_chan_cache_bypass_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_cache_chan_cache_bypass_count`\nFROM metrics_filter(\"sgw_cache_chan_cache_bypass_count\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_cache_chan_cache_channels_added",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_cache_chan_cache_channels_added`\nFROM metrics_filter(\"sgw_cache_chan_cache_channels_added\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_cache_chan_cache_channels_evicted_inactive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_cache_chan_cache_channels_evicted_inactive`\nFROM metrics_filter(\"sgw_cache_chan_cache_channels_evicted_inactive\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_cache_chan_cache_channels_evicted_nru",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_cache_chan_cache_channels_evicted_nru`\nFROM metrics_filter(\"sgw_cache_chan_cache_channels_evicted_nru\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_cache_chan_cache_compact_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_cache_chan_cache_compact_count`\nFROM metrics_filter(\"sgw_cache_chan_cache_compact_count\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_cache_abandoned_seqs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_cache_abandoned_seqs`\nFROM metrics_filter(\"sgw_cache_abandoned_seqs\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_cache_num_skipped_seqs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_cache_num_skipped_seqs`\nFROM metrics_filter(\"sgw_cache_num_skipped_seqs\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_cache_high_seq_cached",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_cache_high_seq_cached`\nFROM metrics_filter(\"sgw_cache_high_seq_cached\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_cache_high_seq_stable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_cache_high_seq_stable`\nFROM metrics_filter(\"sgw_cache_high_seq_stable\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_cache_skipped_seq_len",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_cache_skipped_seq_len`\nFROM metrics_filter(\"sgw_cache_skipped_seq_len\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_cache_pending_seq_len",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_cache_pending_seq_len`\nFROM metrics_filter(\"sgw_cache_pending_seq_len\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_cache_num_skipped_seqs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_cache_num_skipped_seqs`\nFROM metrics_filter(\"sgw_cache_num_skipped_seqs\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_cache_current_skipped_seq_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_cache_current_skipped_seq_count`\nFROM metrics_filter(\"sgw_cache_current_skipped_seq_count\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_database_sequence_get_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_database_sequence_get_count`\nFROM metrics_filter(\"sgw_database_sequence_get_count\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": " sgw_database_sequence_incr_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_database_sequence_incr_count`\nFROM metrics_filter(\"sgw_database_sequence_incr_count\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_database_sequence_reserved_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_database_sequence_reserved_count`\nFROM metrics_filter(\"sgw_database_sequence_reserved_count\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_database_sequence_assigned_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_database_sequence_assigned_count`\nFROM metrics_filter(\"sgw_database_sequence_assigned_count\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_database_sequence_released_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_database_sequence_released_count`\nFROM metrics_filter(\"sgw_database_sequence_released_count\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_database_crc32c_match_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_database_crc32c_match_count`\nFROM metrics_filter(\"sgw_database_crc32c_match_count\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_database_num_replications_active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_database_num_replications_active`\nFROM metrics_filter(\"sgw_database_num_replications_active\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_database_num_replications_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_database_num_replications_total`\nFROM metrics_filter(\"sgw_database_num_replications_total\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_database_num_doc_writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_database_num_doc_writes`\nFROM metrics_filter(\"sgw_database_num_doc_writes\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_database_num_tombstones_compacted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_database_num_tombstones_compacted`\nFROM metrics_filter(\"sgw_database_num_tombstones_compacted\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_database_doc_writes_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_database_doc_writes_bytes`\nFROM metrics_filter(\"sgw_database_doc_writes_bytes\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_database_doc_writes_xattr_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_database_doc_writes_xattr_bytes`\nFROM metrics_filter(\"sgw_database_doc_writes_xattr_bytes\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_database_num_doc_reads_rest",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_database_num_doc_reads_rest`\nFROM metrics_filter(\"sgw_database_num_doc_reads_rest\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_database_num_doc_reads_blip",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_database_num_doc_reads_blip`\nFROM metrics_filter(\"sgw_database_num_doc_reads_blip\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_database_doc_writes_bytes_blip",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 216 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_database_doc_writes_bytes_blip`\nFROM metrics_filter(\"sgw_database_doc_writes_bytes_blip\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  },
  {
   "title": "sgw_database_doc_reads_bytes_blip",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 216 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `sgw_database_doc_reads_bytes_blip`\nFROM metrics_filter(\"sgw_database_doc_reads_bytes_blip\", '$snapshot', NULL, NULL) AS d\nUNNEST _timeseries(d, {\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t) AND (d.labels.`database` = '$database' OR '$database' = \"\")"
    }
   ]
  }
 ]
}