{
 "title": "system_basic",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "snapshot",
    "label": "Job",
    "query": "SELECT DISTINCT d.labels.job FROM cbmonitor._default._default AS d WHERE d.labels.job IS NOT NULL"
   }
  ]
 },
 "panels": [
  {
   "title": "System CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM cbmonitor._default._default AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE d.metric_name=\"sys_cpu_utilization_rate\"\n  AND ('$snapshot'='All' OR d.labels.job='$snapshot')\n  AND d.labels.instance = \"172.23.96.97:8091\"\n  AND time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM cbmonitor._default._default AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE d.metric_name=\"sys_cpu_utilization_rate\"\n  AND ('$snapshot'='All' OR d.labels.job='$snapshot')\n  AND d.labels.instance = \"172.23.96.223:8091\"\n  AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "System Free Memory (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM metrics_filter(\"sys_mem_free\", '$snapshot', \"172.23.96.223:8091\", NULL) AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM metrics_filter(\"sys_mem_free\", '$snapshot', \"172.23.96.97:8091\", NULL) AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "CPU Cores Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM metrics_filter(\"sys_cpu_cores_available\", '$snapshot', \"172.23.96.223:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM metrics_filter(\"sys_cpu_cores_available\", '$snapshot', \"172.23.96.97:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "System Disk Queue (Aggregate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM metrics_filter(\"sys_disk_queue\", '$snapshot', \"172.23.96.223:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM metrics_filter(\"sys_disk_queue\", '$snapshot', \"172.23.96.97:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "Couch Docs Actual Disk Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS cbmonitor\nFROM metrics_filter(\"couch_docs_actual_disk_size\", '$snapshot', NULL, \"cbmonitor\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS metadata\nFROM metrics_filter(\"couch_docs_actual_disk_size\", '$snapshot', NULL, \"metadata\") AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "Scrape Duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM metrics_filter(\"scrape_duration_seconds\", '$snapshot', \"172.23.96.223:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM metrics_filter(\"scrape_duration_seconds\", '$snapshot', \"172.23.96.97:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "memcached CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM cbmonitor._default._default AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE d.metric_name=\"sysproc_cpu_utilization\" AND d.labels.proc=\"memcached\" AND ('$snapshot'='All' OR d.labels.job='$snapshot') AND d.labels.instance=\"172.23.96.97:8091\" AND time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM cbmonitor._default._default AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE d.metric_name=\"sysproc_cpu_utilization\" AND d.labels.proc=\"memcached\" AND ('$snapshot'='All' OR d.labels.job='$snapshot') AND d.labels.instance=\"172.23.96.223:8091\" AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "memcached Resident Memory (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM cbmonitor._default._default AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE d.metric_name=\"sysproc_mem_resident\" AND d.labels.proc=\"memcached\" AND ('$snapshot'='All' OR d.labels.job='$snapshot') AND d.labels.instance=\"172.23.96.97:8091\" AND time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM cbmonitor._default._default AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE d.metric_name=\"sysproc_mem_resident\" AND d.labels.proc=\"memcached\" AND ('$snapshot'='All' OR d.labels.job='$snapshot') AND d.labels.instance=\"172.23.96.223:8091\" AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "ns_server CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM cbmonitor._default._default AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE d.metric_name=\"sysproc_cpu_utilization\" AND d.labels.proc=\"ns_server\" AND ('$snapshot'='All' OR d.labels.job='$snapshot') AND d.labels.instance=\"172.23.96.97:8091\" AND time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM cbmonitor._default._default AS d\nUNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t\nWHERE d.metric_name=\"sysproc_cpu_utilization\" AND d.labels.proc=\"ns_server\" AND ('$snapshot'='All' OR d.labels.job='$snapshot') AND d.labels.instance=\"172.23.96.223:8091\" AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "ns_server Resident Memory (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM cbmonitor._default._default AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE d.metric_name=\"sysproc_mem_resident\" AND d.labels.proc=\"ns_server\" AND ('$snapshot'='All' OR d.labels.job='$snapshot') AND d.labels.instance=\"172.23.96.97:8091\" AND time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM cbmonitor._default._default AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE d.metric_name=\"sysproc_mem_resident\" AND d.labels.proc=\"ns_server\" AND ('$snapshot'='All' OR d.labels.job='$snapshot') AND d.labels.instance=\"172.23.96.223:8091\" AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "cbq-engine CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM metrics_filter(\"sysproc_cpu_utilization\", '$snapshot',\"172.23.96.97:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE d.labels.proc=\"cbq-engine\" AND time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM metrics_filter(\"sysproc_cpu_utilization\", '$snapshot',\"172.23.96.223:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE d.labels.proc=\"cbq-engine\" AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "cbq-engine Resident Memory (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM metrics_filter(\"sysproc_mem_resident\", '$snapshot',\"172.23.96.97:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE d.labels.proc=\"cbq-engine\" AND time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM metrics_filter(\"sysproc_mem_resident\", '$snapshot',\"172.23.96.223:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE d.labels.proc=\"cbq-engine\" AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "Indexer CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM metrics_filter(\"sysproc_cpu_utilization\", '$snapshot',\"172.23.96.97:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE d.labels.proc=\"indexer\" AND time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM metrics_filter(\"sysproc_cpu_utilization\", '$snapshot',\"172.23.96.223:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE d.labels.proc=\"indexer\" AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "Indexer Resident Memory (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM metrics_filter(\"sysproc_mem_resident\", '$snapshot',\"172.23.96.97:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE d.labels.proc=\"indexer\" AND time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM metrics_filter(\"sysproc_mem_resident\", '$snapshot',\"172.23.96.223:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE d.labels.proc=\"indexer\" AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "KV ep metadata memory (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM metrics_filter(\"kv_ep_meta_data_memory_bytes\", '$snapshot', \"172.23.96.223:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM metrics_filter(\"kv_ep_meta_data_memory_bytes\", '$snapshot', \"172.23.96.97:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "KV ep queue size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM metrics_filter(\"kv_ep_queue_size\", '$snapshot', \"172.23.96.223:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM metrics_filter(\"kv_ep_queue_size\", '$snapshot', \"172.23.96.97:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "KV ep disk queue fill (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM metrics_filter(\"kv_ep_diskqueue_fill\", '$snapshot', \"172.23.96.223:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM metrics_filter(\"kv_ep_diskqueue_fill\", '$snapshot', \"172.23.96.97:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "KV ep disk queue drain (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM metrics_filter(\"kv_ep_diskqueue_drain\", '$snapshot', \"172.23.96.223:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM metrics_filter(\"kv_ep_diskqueue_drain\", '$snapshot', \"172.23.96.97:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "vBucket queue age (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM metrics_filter(\"kv_vb_queue_age_seconds\", '$snapshot', \"172.23.96.223:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM metrics_filter(\"kv_vb_queue_age_seconds\", '$snapshot', \"172.23.96.97:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "vBucket queue size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.223`\nFROM metrics_filter(\"kv_vb_queue_size\", '$snapshot', \"172.23.96.223:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    },
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `172.23.96.97`\nFROM metrics_filter(\"kv_vb_queue_size\", '$snapshot', \"172.23.96.97:8091\", NULL) AS d UNNEST _timeseries(d,{\"ts_ranges\":[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    }
   ]
  }
 ]
}