{
 "title": "System Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "snapshot_id", "label": "Snapshot ID" },
   { "name": "nodes", "label": "Nodes" },
   { "name": "buckets", "label": "Buckets" }
  ]
 },
 "panels": [
  {
   "title": "System CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS CPU, d.labels.instance FROM cbmonitor._default._default AS d UNNEST _timeseries(d,{'ts_ranges':[${__from},${__to}]}) AS t WHERE d.metric_name='sys_cpu_utilization_rate' AND d.labels.job='$snapshot_id' AND d.labels.instance IN ${nodes:json} AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "System Free Memory (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS Memory, d.labels.instance FROM get_metric_for('sys_mem_free', '$snapshot_id', ${nodes:json}, NULL) AS d UNNEST _timeseries(d,{'ts_ranges':[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "CPU Cores Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS Cores, d.labels.instance FROM get_metric_for('sys_cpu_cores_available', '$snapshot_id', ${nodes:json}, NULL) AS d UNNEST _timeseries(d,{'ts_ranges':[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "System Disk Queue (Aggregate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS Items, d.labels.instance FROM get_metric_for('sys_disk_queue', '$snapshot_id', ${nodes:json}, NULL) AS d UNNEST _timeseries(d,{'ts_ranges':[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "Couch Docs Actual Disk Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `(Bytes)`, d.labels.`bucket` FROM get_metric_for('couch_docs_actual_disk_size', '$snapshot_id', NULL, ${buckets:json}) AS d UNNEST _timeseries(d,{'ts_ranges':[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "Scrape Duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS Seconds, d.labels.instance FROM get_metric_for('scrape_duration_seconds', '$snapshot_id', ${nodes:json}, NULL) AS d UNNEST _timeseries(d,{'ts_ranges':[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "memcached CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS CPU, d.labels.instance FROM cbmonitor._default._default AS d UNNEST _timeseries(d,{'ts_ranges':[${__from},${__to}]}) AS t WHERE d.metric_name='sysproc_cpu_utilization' AND d.labels.proc='memcached' AND d.labels.job='$snapshot_id' AND d.labels.instance IN ${nodes:json} AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "memcached Resident Memory (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS Memory, d.labels.instance FROM cbmonitor._default._default AS d UNNEST _timeseries(d,{'ts_ranges':[${__from},${__to}]}) AS t WHERE d.metric_name='sysproc_mem_resident' AND d.labels.proc='memcached' AND d.labels.job='$snapshot_id' AND d.labels.instance IN ${nodes:json} AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "ns_server CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS CPU, d.labels.instance FROM cbmonitor._default._default AS d UNNEST _timeseries(d,{'ts_ranges':[${__from},${__to}]}) AS t WHERE d.metric_name='sysproc_cpu_utilization' AND d.labels.proc='ns_server' AND d.labels.job='$snapshot_id' AND d.labels.instance IN ${nodes:json} AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "ns_server Resident Memory (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS Memory, d.labels.instance FROM cbmonitor._default._default AS d UNNEST _timeseries(d,{'ts_ranges':[${__from},${__to}]}) AS t WHERE d.metric_name='sysproc_mem_resident' AND d.labels.proc='ns_server' AND d.labels.job='$snapshot_id' AND d.labels.instance IN ${nodes:json} AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "cbq-engine CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS CPU, d.labels.instance FROM get_metric_for('sysproc_cpu_utilization', '$snapshot_id', ${nodes:json}, NULL) AS d UNNEST _timeseries(d,{'ts_ranges':[${__from},${__to}]}) AS t WHERE d.labels.proc='cbq-engine' AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "cbq-engine Resident Memory (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS Memory, d.labels.instance FROM get_metric_for('sysproc_mem_resident', '$snapshot_id', ${nodes:json}, NULL) AS d UNNEST _timeseries(d,{'ts_ranges':[${__from},${__to}]}) AS t WHERE d.labels.proc='cbq-engine' AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "Indexer CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS CPU, d.labels.instance FROM get_metric_for('sysproc_cpu_utilization', '$snapshot_id', ${nodes:json}, NULL) AS d UNNEST _timeseries(d,{'ts_ranges':[${__from},${__to}]}) AS t WHERE d.labels.proc='indexer' AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "Indexer Resident Memory (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS Memory, d.labels.instance FROM get_metric_for('sysproc_mem_resident', '$snapshot_id', ${nodes:json}, NULL) AS d UNNEST _timeseries(d,{'ts_ranges':[${__from},${__to}]}) AS t WHERE d.labels.proc='indexer' AND time_range(t._t)"
    }
   ]
  },
  {
   "title": "KV EP Metadata Memory (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS Memory, d.labels.instance FROM get_metric_for('kv_ep_meta_data_memory_bytes', '$snapshot_id', ${nodes:json}, NULL) AS d UNNEST _timeseries(d,{'ts_ranges':[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "KV EP Queue Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS Items, d.labels.instance FROM get_metric_for('kv_ep_queue_size', '$snapshot_id', ${nodes:json}, NULL) AS d UNNEST _timeseries(d,{'ts_ranges':[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "KV EP Disk Queue Fill (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS Fill, d.labels.instance FROM get_metric_for('kv_ep_diskqueue_fill', '$snapshot_id', ${nodes:json}, NULL) AS d UNNEST _timeseries(d,{'ts_ranges':[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "KV EP Disk Queue Drain (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS Drain, d.labels.instance FROM get_metric_for('kv_ep_diskqueue_drain', '$snapshot_id', ${nodes:json}, NULL) AS d UNNEST _timeseries(d,{'ts_ranges':[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "vBucket Queue Age (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `(Seconds)`, d.labels.instance FROM get_metric_for('kv_vb_queue_age_seconds', '$snapshot_id', ${nodes:json}, NULL) AS d UNNEST _timeseries(d,{'ts_ranges':[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    }
   ]
  },
  {
   "title": "vBucket Queue Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT MILLIS_TO_STR(t._t) AS time, t._v0 AS `(Bytes)`, d.labels.instance FROM get_metric_for('kv_vb_queue_size', '$snapshot_id', ${nodes:json}, NULL) AS d UNNEST _timeseries(d,{'ts_ranges':[${__from},${__to}]}) AS t WHERE time_range(t._t)"
    }
   ]
  }
 ]
}